[package]
name = "btc_app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bip39 = { version = "2.0.0", features = ["rand"] }
bitcoin = {version =  "0.32.2",features = ["default","rand"]}
hex = "0.4.3"
thiserror = "1.0.61"
